import im_tee_bad_habits_tobacco from './produces/tee-bad-habits-tobacco.jpg';
import im_grey_tshirt from './produces/grey_tshirt.jpg';
import im_orange_jacket from './produces/orange_jacket.jpg';
import im_be_kind_tshirt from './produces/t_shirt/be_kind_tshirt.jpg';
import im_basic_turquoise_tshirt from './produces/t_shirt/basic_turquoise_tshirt.jpg';
import im_basic_blue_tshirt from './produces/t_shirt/basic_blue_tshirt.jpg';
import im_basic_black_tshirt from './produces/t_shirt/basic_black_tshirt.jpg';
import im_turquoise_sweater from './produces/sweater/turquoise_sweater.jpg';
import im_misout_sweeter from './produces/sweater/misout_sweeter.jpg';
import im_black_sweater from './produces/sweater/black_sweater.png';
import im_street_gang_jacket from './produces/jacket/street_gang_jacket.jpg';
import im_bomber_jacket from './produces/jacket/bomber_jacket.jpg';
import im_black_white_jacket from './produces/jacket/black_white_jacket.jpg';
import im_grey_hoodie from './produces/hoodie/grey_hoodie.jpg';
import im_grey_hoodi from './produces/hoodie/grey_hoodi.jpg';
import im_drew_hoodie from './produces/hoodie/drew_hoodie.jpg';
import im_brown_hoodie from './produces/hoodie/brown_hoodie.jpg';
import im_uni_cardigan from './produces/cardigan/uni_cardigan.jpg';
import im_mlb_cardigan from './produces/cardigan/mlb_cardigan.jpg';
import im_knit_cardigan from './produces/cardigan/knit_cardigan.jpg';

export const tee_bad_habits_tobacco = im_tee_bad_habits_tobacco;
export const grey_tshirt = im_grey_tshirt;
export const orange_jacket = im_orange_jacket;
export const be_kind_tshirt = im_be_kind_tshirt;
export const turquoise_sweater = im_turquoise_sweater;
export const street_gang_jacket = im_street_gang_jacket;
export const grey_hoodie = im_grey_hoodie;
export const uni_cardigan = im_uni_cardigan;

export const basic_turquoise_tshirt = im_basic_turquoise_tshirt;
export const basic_blue_tshirt = im_basic_blue_tshirt;
export const misout_sweeter = im_misout_sweeter;
export const black_sweater = im_black_sweater;
export const bomber_jacket = im_bomber_jacket;
export const black_white_jacket = im_black_white_jacket;
export const grey_hoodi = im_grey_hoodi;
export const drew_hoodie = im_drew_hoodie;
export const mlb_cardigan = im_mlb_cardigan;
export const knit_cardigan = im_knit_cardigan;